import React, { useState, useEffect } from 'react';
import {
    Tags,
    Plus,
    Edit2,
    Trash2,
    X,
    Loader2,
    AlertCircle,
    Save,
    Package,
    Palette,
    FolderOpen
} from 'lucide-react';
import {
    collection,
    query,
    where,
    getDocs,
    addDoc,
    updateDoc,
    deleteDoc,
    doc,
    serverTimestamp
} from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { useAuth } from '../../contexts/AuthContext';

const COLORS = [
    { name: 'violet', bg: 'bg-violet-100', text: 'text-violet-700', border: 'border-violet-200' },
    { name: 'blue', bg: 'bg-blue-100', text: 'text-blue-700', border: 'border-blue-200' },
    { name: 'emerald', bg: 'bg-emerald-100', text: 'text-emerald-700', border: 'border-emerald-200' },
    { name: 'amber', bg: 'bg-amber-100', text: 'text-amber-700', border: 'border-amber-200' },
    { name: 'red', bg: 'bg-red-100', text: 'text-red-700', border: 'border-red-200' },
    { name: 'pink', bg: 'bg-pink-100', text: 'text-pink-700', border: 'border-pink-200' },
    { name: 'cyan', bg: 'bg-cyan-100', text: 'text-cyan-700', border: 'border-cyan-200' },
    { name: 'orange', bg: 'bg-orange-100', text: 'text-orange-700', border: 'border-orange-200' },
];

export default function Categories() {
    const { businessId } = useAuth();
    const [categories, setCategories] = useState([]);
    const [products, setProducts] = useState([]);
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [showModal, setShowModal] = useState(false);
    const [editingCategory, setEditingCategory] = useState(null);
    const [formData, setFormData] = useState({ name: '', color: 'violet', description: '' });
    const [error, setError] = useState('');

    useEffect(() => {
        if (businessId) {
            fetchData();
        }
    }, [businessId]);

    const fetchData = async () => {
        try {
            setLoading(true);

            // Fetch categories
            const categoriesRef = collection(db, 'categories');
            const categoriesQuery = query(categoriesRef, where('businessId', '==', businessId));
            const categoriesSnap = await getDocs(categoriesQuery);
            const categoriesData = categoriesSnap.docs.map(doc => ({ id: doc.id, ...doc.data() }));

            // Fetch products to count per category
            const productsRef = collection(db, 'products');
            const productsQuery = query(productsRef, where('businessId', '==', businessId));
            const productsSnap = await getDocs(productsQuery);
            const productsData = productsSnap.docs.map(doc => ({ id: doc.id, ...doc.data() }));

            setProducts(productsData);

            // Add product count to categories
            const categoriesWithCount = categoriesData.map(category => ({
                ...category,
                productCount: productsData.filter(p =>
                    p.category?.toLowerCase() === category.name?.toLowerCase()
                ).length
            }));

            // Also get unique categories from products that aren't in the categories collection
            const productCategories = [...new Set(productsData.map(p => p.category).filter(Boolean))];
            const existingCategoryNames = categoriesData.map(c => c.name?.toLowerCase());

            productCategories.forEach(catName => {
                if (!existingCategoryNames.includes(catName.toLowerCase())) {
                    categoriesWithCount.push({
                        id: `auto-${catName}`,
                        name: catName,
                        color: COLORS[Math.floor(Math.random() * COLORS.length)].name,
                        isAutoGenerated: true,
                        productCount: productsData.filter(p => p.category?.toLowerCase() === catName.toLowerCase()).length
                    });
                }
            });

            setCategories(categoriesWithCount);
        } catch (error) {
            console.error('Error fetching categories:', error);
            setError('Failed to load categories');
        } finally {
            setLoading(false);
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError('');
        setSaving(true);

        try {
            const categoryData = {
                businessId,
                name: formData.name.trim(),
                color: formData.color,
                description: formData.description.trim(),
                updatedAt: serverTimestamp()
            };

            if (editingCategory && !editingCategory.isAutoGenerated) {
                const categoryRef = doc(db, 'categories', editingCategory.id);
                await updateDoc(categoryRef, categoryData);
            } else {
                await addDoc(collection(db, 'categories'), {
                    ...categoryData,
                    createdAt: serverTimestamp()
                });
            }

            resetForm();
            fetchData();
        } catch (error) {
            console.error('Error saving category:', error);
            setError('Failed to save category. Please try again.');
        } finally {
            setSaving(false);
        }
    };

    const handleEdit = (category) => {
        setEditingCategory(category);
        setFormData({
            name: category.name || '',
            color: category.color || 'violet',
            description: category.description || ''
        });
        setShowModal(true);
    };

    const handleDelete = async (category) => {
        if (!confirm(`Are you sure you want to delete "${category.name}"? Products in this category will not be deleted.`)) return;

        try {
            if (!category.isAutoGenerated) {
                await deleteDoc(doc(db, 'categories', category.id));
            }
            fetchData();
        } catch (error) {
            console.error('Error deleting category:', error);
            setError('Failed to delete category');
        }
    };

    const resetForm = () => {
        setFormData({ name: '', color: 'violet', description: '' });
        setEditingCategory(null);
        setShowModal(false);
        setError('');
    };

    const getColorClasses = (colorName) => {
        return COLORS.find(c => c.name === colorName) || COLORS[0];
    };

    const totalProducts = products.length;
    const categorizedProducts = products.filter(p => p.category).length;
    const uncategorizedProducts = totalProducts - categorizedProducts;

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div>
                    <h1 className="text-2xl lg:text-3xl font-bold text-gray-900">Categories</h1>
                    <p className="text-gray-500 mt-1">Organize your products into categories</p>
                </div>
                <button
                    onClick={() => setShowModal(true)}
                    className="inline-flex items-center justify-center gap-2 px-4 py-2.5 bg-violet-600 text-white rounded-lg font-medium hover:bg-violet-700 transition-colors shadow-sm"
                >
                    <Plus className="w-5 h-5" />
                    Add Category
                </button>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                <div className="bg-white p-5 rounded-xl border border-gray-100 shadow-sm">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-violet-50 rounded-lg flex items-center justify-center">
                            <Tags className="w-5 h-5 text-violet-600" />
                        </div>
                        <div>
                            <p className="text-2xl font-bold text-gray-900">{categories.length}</p>
                            <p className="text-xs text-gray-500">Categories</p>
                        </div>
                    </div>
                </div>
                <div className="bg-white p-5 rounded-xl border border-gray-100 shadow-sm">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-blue-50 rounded-lg flex items-center justify-center">
                            <Package className="w-5 h-5 text-blue-600" />
                        </div>
                        <div>
                            <p className="text-2xl font-bold text-gray-900">{totalProducts}</p>
                            <p className="text-xs text-gray-500">Total Products</p>
                        </div>
                    </div>
                </div>
                <div className="bg-white p-5 rounded-xl border border-gray-100 shadow-sm">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-emerald-50 rounded-lg flex items-center justify-center">
                            <FolderOpen className="w-5 h-5 text-emerald-600" />
                        </div>
                        <div>
                            <p className="text-2xl font-bold text-gray-900">{categorizedProducts}</p>
                            <p className="text-xs text-gray-500">Categorized</p>
                        </div>
                    </div>
                </div>
                <div className="bg-white p-5 rounded-xl border border-gray-100 shadow-sm">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-amber-50 rounded-lg flex items-center justify-center">
                            <AlertCircle className="w-5 h-5 text-amber-600" />
                        </div>
                        <div>
                            <p className="text-2xl font-bold text-gray-900">{uncategorizedProducts}</p>
                            <p className="text-xs text-gray-500">Uncategorized</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Categories Grid */}
            {loading ? (
                <div className="flex items-center justify-center h-64">
                    <Loader2 className="w-8 h-8 text-violet-600 animate-spin" />
                </div>
            ) : categories.length === 0 ? (
                <div className="text-center py-12 bg-white rounded-xl border border-gray-100">
                    <Tags className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                    <h3 className="text-lg font-medium text-gray-900 mb-1">No categories yet</h3>
                    <p className="text-gray-500 mb-4">Create categories to organize your products</p>
                    <button
                        onClick={() => setShowModal(true)}
                        className="inline-flex items-center gap-2 px-4 py-2 bg-violet-600 text-white rounded-lg font-medium hover:bg-violet-700 transition-colors"
                    >
                        <Plus className="w-4 h-4" />
                        Add Category
                    </button>
                </div>
            ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                    {categories.map((category) => {
                        const colorClasses = getColorClasses(category.color);
                        return (
                            <div
                                key={category.id}
                                className={`bg-white p-5 rounded-xl border ${colorClasses.border} shadow-sm hover:shadow-md transition-all`}
                            >
                                <div className="flex items-start justify-between mb-4">
                                    <div className={`w-12 h-12 ${colorClasses.bg} rounded-xl flex items-center justify-center`}>
                                        <Tags className={`w-6 h-6 ${colorClasses.text}`} />
                                    </div>
                                    <div className="flex items-center gap-1">
                                        <button
                                            onClick={() => handleEdit(category)}
                                            className="p-1.5 text-gray-400 hover:text-violet-600 hover:bg-violet-50 rounded-lg transition-colors"
                                        >
                                            <Edit2 className="w-4 h-4" />
                                        </button>
                                        <button
                                            onClick={() => handleDelete(category)}
                                            className="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                                        >
                                            <Trash2 className="w-4 h-4" />
                                        </button>
                                    </div>
                                </div>
                                <h3 className="font-semibold text-gray-900 mb-1">{category.name}</h3>
                                {category.description && (
                                    <p className="text-sm text-gray-500 mb-3 line-clamp-2">{category.description}</p>
                                )}
                                <div className="flex items-center justify-between pt-3 border-t border-gray-100">
                                    <span className={`inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium rounded-full ${colorClasses.bg} ${colorClasses.text}`}>
                                        <Package className="w-3 h-3" />
                                        {category.productCount} products
                                    </span>
                                    {category.isAutoGenerated && (
                                        <span className="text-xs text-gray-400">Auto-detected</span>
                                    )}
                                </div>
                            </div>
                        );
                    })}
                </div>
            )}

            {/* Add/Edit Modal */}
            {showModal && (
                <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
                    <div className="bg-white rounded-xl w-full max-w-md">
                        <div className="border-b border-gray-100 px-6 py-4 flex items-center justify-between">
                            <h2 className="text-xl font-semibold text-gray-900">
                                {editingCategory ? 'Edit Category' : 'Add New Category'}
                            </h2>
                            <button
                                onClick={resetForm}
                                className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
                            >
                                <X className="w-5 h-5" />
                            </button>
                        </div>

                        <form onSubmit={handleSubmit} className="p-6 space-y-4">
                            {error && (
                                <div className="flex items-center gap-2 p-4 bg-red-50 border border-red-100 rounded-lg text-red-700">
                                    <AlertCircle className="w-5 h-5 shrink-0" />
                                    <p className="text-sm">{error}</p>
                                </div>
                            )}

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Category Name *</label>
                                <input
                                    type="text"
                                    value={formData.name}
                                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                    required
                                    className="w-full px-4 py-2.5 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-violet-100 focus:border-violet-400"
                                    placeholder="e.g., Electronics"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">Color</label>
                                <div className="flex flex-wrap gap-2">
                                    {COLORS.map((color) => (
                                        <button
                                            key={color.name}
                                            type="button"
                                            onClick={() => setFormData({ ...formData, color: color.name })}
                                            className={`w-8 h-8 rounded-lg ${color.bg} border-2 transition-all ${formData.color === color.name
                                                    ? `${color.border} ring-2 ring-offset-2 ring-${color.name}-400`
                                                    : 'border-transparent hover:scale-110'
                                                }`}
                                        />
                                    ))}
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                                <textarea
                                    value={formData.description}
                                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                                    rows={3}
                                    className="w-full px-4 py-2.5 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-violet-100 focus:border-violet-400 resize-none"
                                    placeholder="Optional description..."
                                />
                            </div>

                            <div className="flex items-center justify-end gap-3 pt-4 border-t border-gray-100">
                                <button
                                    type="button"
                                    onClick={resetForm}
                                    className="px-4 py-2.5 border border-gray-200 text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition-colors"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    disabled={saving}
                                    className="inline-flex items-center gap-2 px-4 py-2.5 bg-violet-600 text-white rounded-lg font-medium hover:bg-violet-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    {saving ? (
                                        <Loader2 className="w-4 h-4 animate-spin" />
                                    ) : (
                                        <Save className="w-4 h-4" />
                                    )}
                                    {editingCategory ? 'Update' : 'Create'}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
}
